{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Customers\",\"Dates\",\"Location\",\"Products\",\"Sales\",\"Sales People\",\".Measures\",\"Client Profitability\",\"Date Periods\",\"Outlier Parameters\",\"Metric Table\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.129.1229.0 (24.05)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"CalcGroup\",\"DaxQueryView_Desktop\",\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "discourageImplicitMeasures": true,
    "relationships": [
      {
        "name": "6e6d225c-4c62-4ff8-be58-80eb89fd0657",
        "fromColumn": "Location ID",
        "fromTable": "Sales",
        "toColumn": "Location ID",
        "toTable": "Location"
      },
      {
        "name": "c21b6000-450d-456b-ab27-5397c0ca20d2",
        "fromColumn": "Product ID",
        "fromTable": "Sales",
        "toColumn": "Product ID",
        "toTable": "Products"
      },
      {
        "name": "00457a2a-6a0f-48e1-a5b4-56d0a1c86906",
        "fromColumn": "Customer ID",
        "fromTable": "Sales",
        "toColumn": "Customer ID",
        "toTable": "Customers"
      },
      {
        "name": "a35f6f5c-b2f9-4036-982a-60d7b51602b8",
        "fromColumn": "Sales Person ID",
        "fromTable": "Sales",
        "toColumn": "Salesperson ID",
        "toTable": "Sales People"
      },
      {
        "name": "f94b502e-2613-4942-bb96-ddb243b4e559",
        "fromColumn": "Purchase Date",
        "fromTable": "Sales",
        "toColumn": "Date Key",
        "toTable": "Dates"
      },
      {
        "name": "0c1b15c9-355d-4789-b065-f110bb5fa33b",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Index",
        "fromTable": "Date Periods",
        "toColumn": "Index",
        "toTable": "Client Profitability"
      },
      {
        "name": "065adf30-af85-6698-db70-0ec0032ea2a5",
        "fromColumn": "Category",
        "fromTable": "Parameter",
        "toColumn": "Metric",
        "toTable": "Metric Table"
      },
      {
        "name": "0be54742-261c-cf95-f8f9-c58d4043e4f4",
        "fromColumn": "Category",
        "fromTable": "Metric Parameter",
        "toColumn": "Metric",
        "toTable": "Metric Table"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Customers",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Customer ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "ab6649b9-676a-48c3-b2b9-e52edfbbf771",
            "sourceColumn": "Customer ID",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ac321ad3-979c-4ef4-9fd8-b4b14263bbbb",
            "sourceColumn": "Customer Name",
            "summarizeBy": "none"
          },
          {
            "name": "Profit Groups",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "CALCULATE(",
              "    SELECTEDVALUE('Client Profitability'[Profit Group]),",
              "    FILTER(",
              "        'Client Profitability',",
              "        [Total Profit] >= 'Client Profitability'[Min] &&",
              "        [Total Profit] < 'Client Profitability'[Max]",
              "    )",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "c5d73c02-717d-4544-9dcb-4bdf79cf9122",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Profit Group Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "VAR _ProfitGroup = 'Customers'[Profit Groups] // This column will be used mainly to order the proift groups the way I want in visuals and slicers",
              "RETURN",
              "    SWITCH(",
              "        _ProfitGroup,",
              "        \"Top Clients\", 1,",
              "        \"Good Clients\", 2,",
              "        \"Average Clients\", 3,",
              "        \"Poor Clients\", 4",
              "    )"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "e44c3772-fbd0-4d12-9c6c-c8d38e305d64",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "f4213e9d-1bf4-400e-ba33-bbe883443014",
        "partitions": [
          {
            "name": "Customers",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\conno\\workspace\\projects\\sales_report_pbi\\resources\\sales_data.xlsx\"), null, true),",
                "    Customers_Sheet = Source{[Item=\"Customers\",Kind=\"Sheet\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Customers_Sheet,{{\"Column1\", type text}, {\"Column2\", type text}}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Customer ID\", type text}, {\"Customer Name\", type text}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dates",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "mm/dd/yy",
            "isKey": true,
            "lineageTag": "7bd8ec3c-91b0-4e08-b5c9-0abe995db1ac",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "eadb0616-cd04-4a3f-84d9-646b1ea4d606",
            "sourceColumn": "Year",
            "summarizeBy": "none"
          },
          {
            "name": "QuarterOfYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4fd25e40-8f30-41c8-bf7b-6e40b3d68276",
            "sourceColumn": "QuarterOfYear",
            "summarizeBy": "none"
          },
          {
            "name": "MonthOfYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "98a46c27-f6cc-4c05-82d3-2c9eae6c8dba",
            "sourceColumn": "MonthOfYear",
            "summarizeBy": "none"
          },
          {
            "name": "DayOfMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "30e6e188-8109-45b5-96ae-17a7565843dc",
            "sourceColumn": "DayOfMonth",
            "summarizeBy": "none"
          },
          {
            "name": "DateInt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "fc536486-9395-4343-99f9-ab1ca7c586ef",
            "sourceColumn": "DateInt",
            "summarizeBy": "none"
          },
          {
            "name": "MonthName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "77b412db-884c-4f5c-9116-70903899e141",
            "sourceColumn": "MonthName",
            "summarizeBy": "none"
          },
          {
            "name": "Month & Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "0f8f2cb9-8509-4ecf-a9c3-2d4fa601937c",
            "sourceColumn": "Month & Year",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter & Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "429ea58f-cda3-4523-8b73-54e60bcc29ff",
            "sourceColumn": "Quarter & Year",
            "summarizeBy": "none"
          },
          {
            "name": "DayInWeek",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a518bd76-bcb7-4439-8577-91bb3126850e",
            "sourceColumn": "DayInWeek",
            "summarizeBy": "none"
          },
          {
            "name": "Day of Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0ed0450d-f63a-4720-874c-43c97e9e153f",
            "sourceColumn": "Day of Week",
            "summarizeBy": "none"
          },
          {
            "name": "WeekEnding",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "9e50bbaa-e3a2-4082-a0cb-413e910d964b",
            "sourceColumn": "WeekEnding",
            "summarizeBy": "none"
          },
          {
            "name": "Week Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fd25a195-aa34-41e1-972c-056028a08194",
            "sourceColumn": "Week Number",
            "summarizeBy": "none"
          },
          {
            "name": "MonthnYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "88d688d6-7af7-4009-b4ec-5c77f0f9cb78",
            "sourceColumn": "MonthnYear",
            "summarizeBy": "none"
          },
          {
            "name": "QuarternYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a6ec8cf7-ceef-410a-a056-96722e0729bd",
            "sourceColumn": "QuarternYear",
            "summarizeBy": "none"
          },
          {
            "name": "ShortYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a8d8be78-64b1-47f8-b4b6-7c70f3752220",
            "sourceColumn": "ShortYear",
            "summarizeBy": "none"
          },
          {
            "name": "FY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "efc4a558-e914-4a24-8ba7-569f6281bb9a",
            "sourceColumn": "FY",
            "summarizeBy": "none"
          },
          {
            "name": "Year & Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5206d76f-f80d-4018-a7f5-ddd2fcc7fe00",
            "sourceColumn": "Year & Week",
            "summarizeBy": "none"
          },
          {
            "name": "YearWeekSort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a03d5f0a-a4d4-48b5-90b5-6e016f807fc9",
            "sourceColumn": "YearWeekSort",
            "summarizeBy": "none"
          },
          {
            "name": "Date Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "expression": "Dates[Date]",
            "formatString": "Short Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "1b57bcf3-338b-4344-8468-35922cbb6aa8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a8f23d72-6877-41b2-85d2-9d0b25a34c37",
            "sourceColumn": "Quarter",
            "summarizeBy": "none"
          }
        ],
        "dataCategory": "Time",
        "lineageTag": "c4ec680e-cf8a-4b00-8a82-f1d3d6f65e73",
        "partitions": [
          {
            "name": "Dates",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\conno\\workspace\\projects\\sales_report_pbi\\resources\\sales_data.xlsx\"), null, true),",
                "    Dates_Sheet = Source{[Item=\"Dates\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Dates_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Date\", type date}, {\"Year\", Int64.Type}, {\"QuarterOfYear\", Int64.Type}, {\"MonthOfYear\", Int64.Type}, {\"DayOfMonth\", Int64.Type}, {\"DateInt\", Int64.Type}, {\"MonthName\", type text}, {\"Month & Year\", type date}, {\"Quarter & Year\", type text}, {\"DayInWeek\", Int64.Type}, {\"Day of Week\", type text}, {\"WeekEnding\", type date}, {\"Week Number\", Int64.Type}, {\"MonthnYear\", Int64.Type}, {\"QuarternYear\", Int64.Type}, {\"ShortYear\", Int64.Type}, {\"FY\", type text}, {\"Year & Week\", type text}, {\"YearWeekSort\", Int64.Type}}),",
                "    Created_Quarter_Column = Table.AddColumn(",
                "        #\"Changed Type\",",
                "        \"Quarter\",",
                "        each Text.BeforeDelimiter([#\"Quarter & Year\"], \" \"), type text",
                "    )",
                "in",
                "    Created_Quarter_Column"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Location",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Location ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "b63b2d92-87cf-4a1b-ada4-54287a96facb",
            "sourceColumn": "Location ID",
            "summarizeBy": "none"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "City",
            "dataType": "string",
            "lineageTag": "c6938360-731d-4d72-b0cd-2efdf54e02e3",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "County",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "County",
            "dataType": "string",
            "lineageTag": "7c75f342-144b-456e-8c26-0bcaad101581",
            "sourceColumn": "County",
            "summarizeBy": "none"
          },
          {
            "name": "State Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "StateOrProvince",
            "dataType": "string",
            "lineageTag": "d2c9ffbd-abb6-4032-b8b9-bfa10942d323",
            "sourceColumn": "State Code",
            "summarizeBy": "none"
          },
          {
            "name": "State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "StateOrProvince",
            "dataType": "string",
            "lineageTag": "bdb931dc-dcc8-44de-9600-99fbdcc5cfba",
            "sourceColumn": "State",
            "summarizeBy": "none"
          },
          {
            "name": "Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "City",
            "dataType": "string",
            "lineageTag": "46d5a858-e209-4a75-ab8f-3731ae1c2406",
            "sourceColumn": "Type",
            "summarizeBy": "none"
          },
          {
            "name": "Latitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataCategory": "Latitude",
            "dataType": "double",
            "lineageTag": "a2a54482-a60f-4127-a6c4-db7c9a4fe93a",
            "sourceColumn": "Latitude",
            "summarizeBy": "none"
          },
          {
            "name": "Longitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataCategory": "Longitude",
            "dataType": "double",
            "lineageTag": "8f51ef1a-4482-4211-8ca9-34019452c82c",
            "sourceColumn": "Longitude",
            "summarizeBy": "none"
          },
          {
            "name": "Area Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5483b605-945a-4013-bf0e-0369011795a0",
            "sourceColumn": "Area Code",
            "summarizeBy": "none"
          },
          {
            "name": "Population",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6021a429-7f5b-46a9-a6c8-bff77f4a4e30",
            "sourceColumn": "Population",
            "summarizeBy": "none"
          },
          {
            "name": "Households",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1f8028c0-00a4-49ff-bde2-695d60ed311b",
            "sourceColumn": "Households",
            "summarizeBy": "none"
          },
          {
            "name": "Median Income",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "19fe758d-e720-433f-b245-99f2dcbd7b3d",
            "sourceColumn": "Median Income",
            "summarizeBy": "none"
          },
          {
            "name": "Land Area",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "61a09a01-f0d4-47b2-a9e7-0c976df33cea",
            "sourceColumn": "Land Area",
            "summarizeBy": "none"
          },
          {
            "name": "Water Area",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a9de0348-0e9d-42ee-a0ba-955f4873cd77",
            "sourceColumn": "Water Area",
            "summarizeBy": "none"
          },
          {
            "name": "Time Zone",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fe6498d4-08b7-44cb-88fa-bc07e0ae2d37",
            "sourceColumn": "Time Zone",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6e93cf65-ba1b-45bd-91b9-56b75abc10b9",
        "partitions": [
          {
            "name": "Location",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\conno\\workspace\\projects\\sales_report_pbi\\resources\\sales_data.xlsx\"), null, true),",
                "    Location_Sheet = Source{[Item=\"Location\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Location_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Location ID\", type text}, {\"Name\", type text}, {\"County\", type text}, {\"State Code\", type text}, {\"State\", type text}, {\"Type\", type text}, {\"Latitude\", type number}, {\"Longitude\", type number}, {\"Area Code\", Int64.Type}, {\"Population\", Int64.Type}, {\"Households\", Int64.Type}, {\"Median Income\", Int64.Type}, {\"Land Area\", Int64.Type}, {\"Water Area\", Int64.Type}, {\"Time Zone\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Products",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Product ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "f58a8e6c-f45c-4e7c-81e9-417a7dfd3cec",
            "sourceColumn": "Product ID",
            "summarizeBy": "none"
          },
          {
            "name": "Product Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "81bee368-38dc-43f0-96d5-eaf34cf27d95",
            "sourceColumn": "Product Name",
            "summarizeBy": "none"
          },
          {
            "name": "Cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "0bd68320-bb95-4ad8-a36f-c96f55238b12",
            "sourceColumn": "Cost",
            "summarizeBy": "none"
          },
          {
            "name": "Original Sale Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "55e30cbd-091b-445e-a509-0db982be69b8",
            "sourceColumn": "Original Sale Price",
            "summarizeBy": "none"
          },
          {
            "name": "Discount Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "54be1be7-721f-433a-a55b-8c9c89bc3a86",
            "sourceColumn": "Discount Code",
            "summarizeBy": "none"
          },
          {
            "name": "Discount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7ebe93e0-572b-45ea-93c5-75f7a4b29850",
            "sourceColumn": "Discount",
            "summarizeBy": "none"
          },
          {
            "name": "Current Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "ebc62e14-ef12-4139-889f-27b29ffdc136",
            "sourceColumn": "Current Price",
            "summarizeBy": "none"
          },
          {
            "name": "Taxes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "double",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "b1c1f5c5-f8ef-4664-bd43-4c2e4c69c175",
            "sourceColumn": "Taxes",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6441de5a-80d2-4917-b65a-1dceeee3f8a3",
        "partitions": [
          {
            "name": "Products",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\conno\\workspace\\projects\\sales_report_pbi\\resources\\sales_data.xlsx\"), null, true),",
                "    Products_Sheet = Source{[Item=\"Products\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Products_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Product ID\", type text}, {\"Product Name\", type text}, {\"Cost\", Int64.Type}, {\"Original Sale Price\", Int64.Type}, {\"Discount Code\", type text}, {\"Discount\", Int64.Type}, {\"Current Price\", Int64.Type}, {\"Taxes\", type number}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Sales",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Order ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0f94cd9c-f730-4e45-96e6-d6276e1ea35f",
            "sourceColumn": "Order ID",
            "summarizeBy": "none"
          },
          {
            "name": "Product ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "240c6ba6-96b1-45dc-bd61-bd2eabedbc21",
            "sourceColumn": "Product ID",
            "summarizeBy": "none"
          },
          {
            "name": "Location ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "92faab73-78e1-44ac-b1d2-30b03374c68e",
            "sourceColumn": "Location ID",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Person ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "44254d77-7392-4162-b9d4-ed4c80f88337",
            "sourceColumn": "Sales Person ID",
            "summarizeBy": "none"
          },
          {
            "name": "Customer ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "9bcb8cbb-2a47-4ee0-97b1-c169f8f87ca6",
            "sourceColumn": "Customer ID",
            "summarizeBy": "none"
          },
          {
            "name": "Purchase Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "mm/dd/yy",
            "lineageTag": "cb895f79-ab69-4e0a-9d7e-37f27d772531",
            "sourceColumn": "Purchase Date",
            "summarizeBy": "none"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "36022213-3b2a-4c00-b5ba-945fb14fe50c",
            "sourceColumn": "Quantity",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "7fd06d7a-4dae-4ab7-9f98-5c6bfe07d873",
        "partitions": [
          {
            "name": "Sales",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\conno\\workspace\\projects\\sales_report_pbi\\resources\\sales_data.xlsx\"), null, true),",
                "    Sales_Sheet = Source{[Item=\"Sales\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Sales_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Order ID\", type text}, {\"Product ID\", type text}, {\"Location ID\", type text}, {\"Sales Person ID\", type text}, {\"Customer ID\", type text}, {\"Purchase Date\", type date}, {\"Quantity\", Int64.Type}}),",
                "    MaxDate = List.Max(Dates[Date]),",
                "    // There are 4 more dates than my date table alows so I'm filtering the sales table by the max date of the refrenced table",
                "    FinalTable = Table.SelectRows(",
                "        #\"Changed Type\",",
                "        each [Purchase Date] <= MaxDate",
                "    )",
                "in",
                "    FinalTable"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Sales People",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Salesperson ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "2dd0530e-0415-402d-9a1a-b5e95d1ba49b",
            "sourceColumn": "Salesperson ID",
            "summarizeBy": "none"
          },
          {
            "name": "Salesperson Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8ce2e36c-af5e-4306-8879-3de772085594",
            "sourceColumn": "Salesperson Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "97f504cb-a73c-400b-ad86-10b23e46bda6",
        "partitions": [
          {
            "name": "Sales People",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\conno\\workspace\\projects\\sales_report_pbi\\resources\\sales_data.xlsx\"), null, true),",
                "    #\"Sales People_Sheet\" = Source{[Item=\"Sales People\",Kind=\"Sheet\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Sales People_Sheet\",{{\"Column1\", type text}, {\"Column2\", type text}}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Salesperson ID\", type text}, {\"Salesperson Name\", type text}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Calculation group",
        "calculationGroup": {
          "calculationItems": [
            {
              "name": "CY",
              "expression": "SELECTEDMEASURE()"
            },
            {
              "name": "LY",
              "expression": [
                "",
                "CALCULATE(",
                "    SELECTEDMEASURE(),",
                "    DATEADD(Dates[Date], -1, YEAR)",
                ")"
              ]
            }
          ]
        },
        "columns": [
          {
            "name": "Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1001ae11-e7ca-4ba1-8ef2-319de9ba5f2f",
            "sortByColumn": "Ordinal",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Ordinal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "72055ad0-f298-4ef0-9f9f-6fd9987bd58b",
            "sourceColumn": "Ordinal",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "847f54c1-44b6-4c9c-9116-22929e1b464b",
        "partitions": [
          {
            "name": "Calculation group",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": ".Measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "Name"
          }
        ],
        "lineageTag": "240f4719-1a08-4ab3-b99c-644b962aa80e",
        "measures": [
          {
            "name": "Total Cost",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Base Measires",
            "expression": "SUMX(Sales, Sales[Quantity] * RELATED(Products[Cost]) )",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "e60b7452-997a-441e-9835-6b5646299b46"
          },
          {
            "name": "Total Profit",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Base Measires",
            "expression": "[Total Sales] - [Total Cost]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "cb0778c9-d5d0-4d0f-8af9-3d2962b07e06"
          },
          {
            "name": "Total Profit Margin",
            "displayFolder": "Base Measires",
            "expression": "DIVIDE([Total Profit], [Total Sales], 0)",
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "lineageTag": "2ff80cd5-5374-4495-b517-56992817f03f"
          },
          {
            "name": "Total Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Base Measires",
            "expression": "SUMX(Sales, Sales[Quantity] * RELATED(Products[Current Price]) )",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "9238440c-594b-4595-a000-41e8d04afbf3"
          },
          {
            "name": "Top 20% Cust Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Key Measures",
            "expression": [
              "VAR _CustomerPercent = DISTINCTCOUNT(Sales[Customer ID]) * 0.2",
              "RETURN",
              "    CALCULATE(",
              "        [Total Sales],",
              "        FILTER(",
              "            VALUES(Sales[Customer ID]),",
              "            RANKX(VALUES(Sales[Customer ID]), [Total Sales],,DESC) <= _CustomerPercent",
              "        )",
              "    )"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "d64b220b-3564-474c-aa2b-84fe603cf9f4"
          },
          {
            "name": "%Share Total Sales",
            "displayFolder": "Key Measures",
            "expression": "DIVIDE([Top 20% Cust Sales], [Total Sales], 0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "35aafef7-3c57-4cec-9266-ed91f7ecbb7a"
          },
          {
            "name": "Profits by Customer Groups",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Key Measures",
            "expression": [
              "VAR _CustomerNames = VALUES(Customers[Customer Name])",
              "RETURN",
              "CALCULATE(",
              "    [Total Profit],",
              "    FILTER(_CustomerNames,",
              "        COUNTROWS(",
              "            FILTER(",
              "                'Client Profitability',",
              "                [Total Profit] >= 'Client Profitability'[Min] &&",
              "                [Total Profit] < 'Client Profitability'[Max]",
              "            )",
              "        ) >0",
              "    )",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "34de6e07-6da6-4e82-8d41-afecfa647ac5"
          },
          {
            "name": "Customer Count",
            "displayFolder": "Key Measures",
            "expression": "DISTINCTCOUNT('Customers'[Customer Name])",
            "formatString": "0",
            "lineageTag": "92ff098a-5b12-4d82-9435-2fa2334b6c66"
          },
          {
            "name": "Profit Groups (Plot Order Index)",
            "displayFolder": "Formatting Measures",
            "expression": "VALUES('Customers'[Profit Group Index])",
            "formatString": "0",
            "lineageTag": "bdb0c799-8845-4f72-9e86-1328eea11b3f"
          },
          {
            "name": "Total Sales YA",
            "displayFolder": "Base Measires",
            "expression": "CALCULATE([Total Sales], SAMEPERIODLASTYEAR('Dates'[Date]) )",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "7dc8c95d-083a-458f-bf94-e34b65ed08e1"
          },
          {
            "name": "%Sales Δ",
            "displayFolder": "Key Measures",
            "expression": "DIVIDE([Total Sales] - [Total Sales YA], [Total Sales YA])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "227b6648-fb59-4c49-ad81-743ac7137318"
          },
          {
            "name": "Cummulative Sales",
            "displayFolder": "Key Measures",
            "expression": [
              "CALCULATE( ",
              "\t[Sales - Brand Parameter], ",
              "\tFILTER(",
              "\t\tALL(Dates[Date]),",
              "\t\tDates[Date] <= MAX(Dates[Date])",
              "\t)",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "fd9857e8-4a74-49e7-ae7a-a6b84bab0496"
          },
          {
            "name": "Cummulative Cost",
            "displayFolder": "Key Measures",
            "expression": [
              "CALCULATE(",
              "    [Cost - Brand Parameter],",
              "    FILTER(",
              "        ALL(Dates[Date]),",
              "        Dates[Date] <= MAX(Dates[Date])",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "748fca41-55cc-4f78-9b96-dfe1b2136ef3"
          },
          {
            "name": "Total Cost YA",
            "displayFolder": "Base Measires",
            "expression": "CALCULATE([Total Cost], SAMEPERIODLASTYEAR(Dates[Date]) )",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "1d30a2b4-26f0-4e45-8330-f2c9c2036af3"
          },
          {
            "name": "Total Profit YA",
            "displayFolder": "Base Measires",
            "expression": "CALCULATE([Total Profit], SAMEPERIODLASTYEAR(Dates[Date]) )",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "1843b366-59a1-445d-9502-c2fa65ef9c1e"
          },
          {
            "name": "%Cost Δ",
            "displayFolder": "Key Measures",
            "expression": "DIVIDE([Total Cost] - [Total Cost YA], [Total Cost YA])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "352ce6de-37be-46ef-b420-bcca46e8b0c2"
          },
          {
            "name": "%Profit Δ",
            "displayFolder": "Key Measures",
            "expression": "DIVIDE([Total Profit] - [Total Profit YA], [Total Profit YA])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f9aa612c-4c82-40a9-9bcb-f92577cdfaf8"
          },
          {
            "name": "%Share Top Cust YA",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Key Measures",
            "expression": "DIVIDE([Top 20% Cust Sales], [Total Sales], 0)",
            "lineageTag": "07dcc523-9c07-4ffd-9326-a8fba68f17b8"
          },
          {
            "name": "Profit - Brand Parameter",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "description": "Returns value with the brand parameter applied",
            "displayFolder": "Key Measures\\.Brand Parameter",
            "expression": [
              "CALCULATE(",
              "        [Total Profit],",
              "        KEEPFILTERS(",
              "            WINDOW(",
              "                1,ABS,",
              "                [Products Parameter Value],ABS,",
              "                ADDCOLUMNS(",
              "                    SUMMARIZE(",
              "                        ALLSELECTED('Products'),",
              "                        'Products'[Product Name]",
              "                    ),",
              "                    \"Top Products\", [Total Sales]",
              "                ),",
              "                ORDERBY([Top Products], DESC)",
              "            )",
              "        )",
              "    )"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "ebd55a67-9520-4c09-82a2-1a7a0b74673b"
          },
          {
            "name": "Profit YA - Brand Parameter",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "description": "Returns value with the brand parameter applied",
            "displayFolder": "Key Measures\\.Brand Parameter",
            "expression": [
              "CALCULATE(",
              "        [Total Profit YA],",
              "        KEEPFILTERS(",
              "            WINDOW(",
              "                1,ABS,",
              "                [Products Parameter Value],ABS,",
              "                ADDCOLUMNS(",
              "                    SUMMARIZE(",
              "                        ALLSELECTED('Products'),",
              "                        'Products'[Product Name]",
              "                    ),",
              "                    \"Top Products\", [Total Sales]",
              "                ),",
              "                ORDERBY([Top Products], DESC)",
              "            )",
              "        )",
              "    )"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "fce66972-9071-4406-8769-4daa8b6ca2ae"
          },
          {
            "name": "Cost - Brand Parameter",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "description": "Returns value with the brand parameter applied",
            "displayFolder": "Key Measures\\.Brand Parameter",
            "expression": [
              "CALCULATE(",
              "        [Total Cost],",
              "        KEEPFILTERS(",
              "            WINDOW(",
              "                1,ABS,",
              "                [Products Parameter Value],ABS,",
              "                ADDCOLUMNS(",
              "                    SUMMARIZE(",
              "                        ALLSELECTED('Products'),",
              "                        'Products'[Product Name]",
              "                    ),",
              "                    \"Top Products\", [Total Sales]",
              "                ),",
              "                ORDERBY([Top Products], DESC)",
              "            )",
              "        )",
              "    )"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "32e67394-2c92-45da-b96e-2fd8d3b593e1"
          },
          {
            "name": "Cost YA - Brand Parameter",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "description": "Returns value with the brand parameter applied",
            "displayFolder": "Key Measures\\.Brand Parameter",
            "expression": [
              "CALCULATE(",
              "        [Total Cost YA],",
              "        KEEPFILTERS(",
              "            WINDOW(",
              "                1,ABS,",
              "                [Products Parameter Value],ABS,",
              "                ADDCOLUMNS(",
              "                    SUMMARIZE(",
              "                        ALLSELECTED('Products'),",
              "                        'Products'[Product Name]",
              "                    ),",
              "                    \"Top Products\", [Total Sales]",
              "                ),",
              "                ORDERBY([Top Products], DESC)",
              "            )",
              "        )",
              "    )"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "2633f324-8a22-4f80-a475-f5dedae1cdac"
          },
          {
            "name": "Sales - Brand Parameter",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "description": "Returns value with the brand parameter applied",
            "displayFolder": "Key Measures\\.Brand Parameter",
            "expression": [
              "CALCULATE(",
              "        [Total Sales],",
              "        KEEPFILTERS(",
              "            WINDOW(",
              "                1,ABS,",
              "                [Products Parameter Value],ABS,",
              "                ADDCOLUMNS(",
              "                    SUMMARIZE(",
              "                        ALLSELECTED('Products'),",
              "                        'Products'[Product Name]",
              "                    ),",
              "                    \"Top Products\", [Total Sales]",
              "                ),",
              "                ORDERBY([Top Products], DESC)",
              "            )",
              "        )",
              "    )"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "59dc69e3-4d0c-4ad1-a754-0841d2832559"
          },
          {
            "name": "Sales YA - Brand Parameter",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "description": "Returns value with the brand parameter applied",
            "displayFolder": "Key Measures\\.Brand Parameter",
            "expression": [
              "CALCULATE(",
              "        [Total Sales YA],",
              "        KEEPFILTERS(",
              "            WINDOW(",
              "                1,ABS,",
              "                [Products Parameter Value],ABS,",
              "                ADDCOLUMNS(",
              "                    SUMMARIZE(",
              "                        ALLSELECTED('Products'),",
              "                        'Products'[Product Name]",
              "                    ),",
              "                    \"Top Products\", [Total Sales]",
              "                ),",
              "                ORDERBY([Top Products], DESC)",
              "            )",
              "        )",
              "    )"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "a811d41b-7093-4fc4-a5ec-6a6a543c873f"
          },
          {
            "name": "Profit Margin - Brand Parameter",
            "description": "Returns value with the brand parameter applied",
            "displayFolder": "Key Measures\\.Brand Parameter",
            "expression": [
              "CALCULATE(",
              "        [Total Profit Margin],",
              "        KEEPFILTERS(",
              "            WINDOW(",
              "                1,ABS,",
              "                [Products Parameter Value],ABS,",
              "                ADDCOLUMNS(",
              "                    SUMMARIZE(",
              "                        ALLSELECTED('Products'),",
              "                        'Products'[Product Name]",
              "                    ),",
              "                    \"Top Products\", [Total Sales]",
              "                ),",
              "                ORDERBY([Top Products], DESC)",
              "            )",
              "        )",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "4b34250c-fc92-42bc-a8bb-1ff40fcfa4ee"
          },
          {
            "name": "%Cost Δ - Brand Parameter",
            "description": "Returns value with the brand parameter applied",
            "displayFolder": "Key Measures\\.Brand Parameter",
            "expression": [
              "CALCULATE(",
              "    DIVIDE([Total Cost] - [Total Cost YA], [Total Cost YA]),",
              "    KEEPFILTERS(",
              "            WINDOW(",
              "                1,ABS,",
              "                [Products Parameter Value],ABS,",
              "                ADDCOLUMNS(",
              "                    SUMMARIZE(",
              "                        ALLSELECTED('Products'),",
              "                        'Products'[Product Name]",
              "                    ),",
              "                    \"Top Products\", [Total Sales]",
              "                ),",
              "                ORDERBY([Top Products], DESC)",
              "            )",
              "        )",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "4bda12fd-828f-43de-a04d-ad39baa870d1"
          },
          {
            "name": "%Sales Δ - Brand Parameter",
            "description": "Returns value with the brand parameter applied",
            "displayFolder": "Key Measures\\.Brand Parameter",
            "expression": [
              "CALCULATE(",
              "    DIVIDE([Total Sales] - [Total Sales YA], [Total Sales YA]),",
              "    KEEPFILTERS(",
              "            WINDOW(",
              "                1,ABS,",
              "                [Products Parameter Value],ABS,",
              "                ADDCOLUMNS(",
              "                    SUMMARIZE(",
              "                        ALLSELECTED('Products'),",
              "                        'Products'[Product Name]",
              "                    ),",
              "                    \"Top Products\", [Total Sales]",
              "                ),",
              "                ORDERBY([Top Products], DESC)",
              "            )",
              "        )",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "8e345f8c-8ea9-49d4-81dc-8db94ae76374"
          },
          {
            "name": "%Profit Δ - Brand Parameter",
            "description": "Returns value with the brand parameter applied",
            "displayFolder": "Key Measures\\.Brand Parameter",
            "expression": [
              "CALCULATE(",
              "    DIVIDE([Total Profit] - [Total Profit YA], [Total Profit YA]),",
              "    KEEPFILTERS(",
              "            WINDOW(",
              "                1,ABS,",
              "                [Products Parameter Value],ABS,",
              "                ADDCOLUMNS(",
              "                    SUMMARIZE(",
              "                        ALLSELECTED('Products'),",
              "                        'Products'[Product Name]",
              "                    ),",
              "                    \"Top Products\", [Total Sales]",
              "                ),",
              "                ORDERBY([Top Products], DESC)",
              "            )",
              "        )",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "649da741-364f-4fcc-93ae-b4b438d20511"
          },
          {
            "name": "Max value",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Key Measures\\.IBCS",
            "expression": [
              "IF(",
              "\t\t[Sales - IBCS]>[Sales YA - IBCS], ",
              "\t\t[Sales - IBCS], ",
              "\t\t[Sales YA - IBCS]",
              "\t)"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "20ea8022-eaa7-4402-a177-466e74f67925"
          },
          {
            "name": "Red Max",
            "displayFolder": "Key Measures\\.IBCS",
            "expression": [
              "If(",
              "\t\t[Sales Δ - IBCS] < 0, ",
              "\t\t[Max value]",
              "\t)"
            ],
            "lineageTag": "6869fd1f-2240-4c3a-90a9-8923f02b2189"
          },
          {
            "name": "Green Max",
            "displayFolder": "Key Measures\\.IBCS",
            "expression": [
              "If(",
              "\t\t[Sales Δ - IBCS] > 0, ",
              "\t\t[Max value]",
              "\t)"
            ],
            "lineageTag": "ff9a7509-b730-4059-952b-30e0d6fe8156"
          },
          {
            "name": "Sales - IBCS",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Key Measures\\.IBCS",
            "expression": "[Sales - Brand Parameter]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "bfe0b1fe-df0d-4479-9213-da4683e70149"
          },
          {
            "name": "Sales YA - IBCS",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Key Measures\\.IBCS",
            "expression": "[Sales YA - Brand Parameter]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "8182cbba-c2b8-477a-a8c5-9afb82676671"
          },
          {
            "name": "%Sales Δ - IBCS",
            "displayFolder": "Key Measures\\.IBCS",
            "expression": "DIVIDE ([Sales Δ - IBCS], [Sales YA - IBCS])",
            "formatString": "0%;-0%;0%",
            "lineageTag": "4a73bbf6-78a5-4986-8798-3e39e3dedb98"
          },
          {
            "name": "Delta Color",
            "displayFolder": "Key Measures\\.IBCS",
            "expression": [
              "IF(",
              "\t\t[Sales Δ - IBCS] < 0,  ",
              "\t\t\"#BD3978\",",
              "\t\t\"#14ABD1\"",
              "\t)"
            ],
            "lineageTag": "ae8cb17a-c01e-409c-91dd-e409c8d6cef5"
          },
          {
            "name": "Sales Δ - IBCS",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Key Measures\\.IBCS",
            "expression": "[Sales - IBCS] - [Sales YA - IBCS]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "bf174a00-f510-45b8-835a-1cb5f4f87de2"
          },
          {
            "name": "Cummulative Profit",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Key Measures",
            "expression": [
              "CALCULATE( ",
              "\t[Profit - Brand Parameter], ",
              "\tFILTER(",
              "\t\tALL(Dates[Date]),",
              "\t\tDates[Date] <= MAX(Dates[Date])",
              "\t)",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "30990fc8-c33d-4eff-b02b-d5f71d17036e"
          }
        ],
        "partitions": [
          {
            "name": ".Measures",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Client Profitability",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Profit Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ffa5274f-b2ec-4256-8600-020be20df184",
            "sourceColumn": "Profit Group",
            "summarizeBy": "none"
          },
          {
            "name": "Min",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "a208df27-7da0-4a24-b281-fc34df005951",
            "sourceColumn": "Min",
            "summarizeBy": "sum"
          },
          {
            "name": "Max",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "6cbbf2e3-07e7-407f-8f52-44b6394db56c",
            "sourceColumn": "Max",
            "summarizeBy": "sum"
          },
          {
            "name": "Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "493f93e3-dd5d-4200-8641-c0e376ab4550",
            "sourceColumn": "Index",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "313f1a97-19f5-4639-9c7b-c7bc5fe251a2",
        "partitions": [
          {
            "name": "Client Profitability",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WCskvUHDOyUzNKylW0lEyMjUwMADShgZQoBSrE63knp+fgqzIAKIIohikwLEstSgxPRVJjaERVA3ckID8/CIkBQZwRbGxAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Profit Group\" = _t, Min = _t, Max = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Profit Group\", type text}, {\"Min\", Int64.Type}, {\"Max\", Int64.Type}}),",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Changed Type\", \"Index\", 0, 1, Int64.Type)",
                "in",
                "    #\"Added Index\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Date Periods",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Periods",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "d77c3e03-eb21-490a-8db9-495d3d5f1621",
            "sortByColumn": "Index",
            "sourceColumn": "Periods",
            "summarizeBy": "none"
          },
          {
            "name": "Starting Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    'Date Periods'[Periods] = \"2 Year\", MAX(Dates[Date]) - 730,",
              "    'Date Periods'[Periods] = \"1 Year\", MAX(Dates[Date]) - 365,",
              "    'Date Periods'[Periods] = \"6 Months\", MAX(Dates[Date]) - 175,",
              "    'Date Periods'[Periods] = \"3 Months\", MAX(Dates[Date]) - 84,",
              "    'Date Periods'[Periods] = \"4 Weeks\", MAX(Dates[Date]) - 21",
              ")"
            ],
            "formatString": "mm/dd/yy",
            "isDataTypeInferred": true,
            "lineageTag": "7598e947-13c8-4c07-b6b8-5c3b7ba4345e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "25d3e6cc-80d5-4330-9b2c-3d54ddcdddcb",
            "sourceColumn": "Index",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "058f8d76-1387-48d5-ba2b-3fb54eaebe47",
        "partitions": [
          {
            "name": "Date Periods",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMlKITE0sUorViVYyRDDNFHzz80oyisEcY2SOiUJ4amo2kB0LAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Periods = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Periods\", type text}}),",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Changed Type\", \"Index\", 0, 1, Int64.Type)",
                "in",
                "    #\"Added Index\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Outlier Parameters",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Grouping",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9af582a9-9cf8-4688-a0a0-985078417e9d",
            "sourceColumn": "Grouping",
            "summarizeBy": "none"
          },
          {
            "name": "Profit Margin Min",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "8b63a9a7-51bd-4dcb-97a1-360be0d1f1e9",
            "sourceColumn": "Profit Margin Min",
            "summarizeBy": "sum"
          },
          {
            "name": "Profit Margin Max",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "0dcbab4c-62ed-4d8b-a904-a7ea7b00488c",
            "sourceColumn": "Profit Margin Max",
            "summarizeBy": "sum"
          },
          {
            "name": "Sales Min",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "38de21f4-0245-4b51-8ccb-7ce917d684d3",
            "sourceColumn": "Sales Min",
            "summarizeBy": "sum"
          },
          {
            "name": "Sales Max",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "int64",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "8e65e6a9-9c78-4874-a2d6-991d33b52968",
            "sourceColumn": "Sales Max",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "e95861be-162a-449f-b3e2-8f5e0784cf28",
        "partitions": [
          {
            "name": "Outlier Parameters",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45W8i8tyclMLVLSUTI2VQWShgYGIErF1FTHwMAAzDIwADNjdaKV/PLzdBE6wCoh2lQMkDTFxgIA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Grouping = _t, #\"Profit Margin Min\" = _t, #\"Profit Margin Max\" = _t, #\"Sales Min\" = _t, #\"Sales Max\" = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Profit Margin Min\", Percentage.Type}, {\"Profit Margin Max\", Percentage.Type}, {\"Sales Min\", Int64.Type}, {\"Sales Max\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Products Parameter",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "4b03787238654c1cad36468e0b6c7065"
          }
        ],
        "columns": [
          {
            "name": "Products Parameter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "version": 0
                }
              }
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "577e6d0b-c086-40f7-9284-0824e0471134",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "4e517807-9e29-4dc4-acaf-3d7a367a8029",
        "measures": [
          {
            "name": "Products Parameter Value",
            "expression": "SELECTEDVALUE('Products Parameter'[Products Parameter], 10)",
            "formatString": "0",
            "lineageTag": "d62197fc-9a6f-48ae-8ca3-4e9b9cf3a0b2"
          }
        ],
        "partitions": [
          {
            "name": "Products Parameter",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(0, 90, 1)",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Metric Parameter",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "456cd7c5792142bcbb8fb8058c6be2a7"
          }
        ],
        "columns": [
          {
            "name": "Metric Parameter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "4ebebc98-aefb-42cf-bb50-db1a551ca35a",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Metric Parameter Fields"
                }
              ]
            },
            "sortByColumn": "Metric Parameter Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Metric Parameter Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "fc91f521-0c32-4204-82b4-46af704f3a69",
            "sortByColumn": "Metric Parameter Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Metric Parameter Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "11304381-421c-40b9-831d-bb7f2f0f3fc8",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "SWITCH(",
              "    TRUE(),",
              "    CONTAINSSTRING('Metric Parameter'[Metric Parameter], \"Cost\"), \"Cost\",",
              "    CONTAINSSTRING('Metric Parameter'[Metric Parameter], \"Sales\"), \"Sales\",",
              "    CONTAINSSTRING('Metric Parameter'[Metric Parameter], \"Profit\"), \"Profit\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "bc818f61-0f28-4774-ab5a-852f98d88fb9",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "76d01ca5-ac07-4694-886e-226fca5a4ed6",
        "partitions": [
          {
            "name": "Metric Parameter",
            "mode": "import",
            "source": {
              "expression": [
                "// Used in Customers report ",
                "{",
                "    (\"%Cost Δ\", NAMEOF('.Measures'[%Cost Δ]), 0),",
                "    (\"%Profit Δ\", NAMEOF('.Measures'[%Profit Δ]), 1),",
                "    (\"%Sales Δ\", NAMEOF('.Measures'[%Sales Δ]), 2),",
                "    (\"Cost\", NAMEOF('.Measures'[Total Cost]), 3),",
                "    (\"Sales\", NAMEOF('.Measures'[Total Sales]), 4),",
                "    (\"Profit\", NAMEOF('.Measures'[Total Profit]), 5)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Parameter",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "353abf6790f74ced8d62fbd5ce0693fa"
          }
        ],
        "columns": [
          {
            "name": "Parameter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "25257da5-0415-460f-9f22-a655279e9fd1",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Parameter Fields"
                }
              ]
            },
            "sortByColumn": "Parameter Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parameter Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "0f49bdcf-c677-4d1c-abad-857cd62fe6f6",
            "sortByColumn": "Parameter Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parameter Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "d45fa83b-24ff-4a1c-a463-ed3f47251c69",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "SWITCH(",
              "    TRUE(),",
              "    CONTAINSSTRING(Parameter[Parameter], \"Cost\"), \"Cost\",",
              "    CONTAINSSTRING(Parameter[Parameter], \"Sales\"), \"Sales\",",
              "    CONTAINSSTRING(Parameter[Parameter], \"Profit\"), \"Profit\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "4da12130-320d-422d-b639-e057af8cd562",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "def771b9-ba46-49ee-89c9-3c7d7e147500",
        "partitions": [
          {
            "name": "Parameter",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"%Cost Δ\", NAMEOF('.Measures'[%Cost Δ - Brand Parameter]), 0),",
                "    (\"%Profit Δ\", NAMEOF('.Measures'[%Profit Δ - Brand Parameter]), 1),",
                "    (\"%Sales Δ\", NAMEOF('.Measures'[%Sales Δ - Brand Parameter]), 2),",
                "    (\"Cummulative Cost\", NAMEOF('.Measures'[Cummulative Cost]), 3),",
                "    (\"Cummulative Profit\", NAMEOF('.Measures'[Cummulative Profit]), 4),",
                "    (\"Cummulative Sales\", NAMEOF('.Measures'[Cummulative Sales]), 5)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Metric Table",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Metric",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "173438b3-b45d-41d9-8faf-796a6ebd9a8e",
            "sourceColumn": "Metric",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "582c830d-8c77-4830-9d76-6c9a46524d87",
        "partitions": [
          {
            "name": "Metric Table",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45Wcs4vLlGK1YlWCk7MSS0GswKK8tMygYKxAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Metric = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Metric\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}