DEFINE
	MEASURE '.Measures'[Profit - Brand Parameter] = CALCULATE(
        [Total Profit],
        KEEPFILTERS(
            WINDOW(
                1,ABS,
                [Products Parameter Value],ABS,
                ADDCOLUMNS(
                    SUMMARIZE(
                        ALLSELECTED('Products'),
                        'Products'[Product Name]
                    ),
                    "Top Products", [Total Profit]
                ),
                ORDERBY([Top Products], DESC)
            )
        )
    )

EVALUATE
	SUMMARIZECOLUMNS(
		"Profit - Brand Parameter", '.Measures'[Profit - Brand Parameter]
	)